// <auto-generated />
using System;
using CreditFullSA.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CreditFullSA.Migrations
{
    [DbContext(typeof(DbContextCreditos))]
    [Migration("20240517205252_Initialcreate")]
    partial class Initialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CreditFullSA.Models.Administrador", b =>
                {
                    b.Property<string>("email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("email");

                    b.ToTable("Administradores");

                    b.HasData(
                        new
                        {
                            email = "jcruz@gmail.com",
                            Nombre = "Jorge Cruz cruz",
                            Password = "78963"
                        },
                        new
                        {
                            email = "jvega@gmail.com",
                            Nombre = "Jinnet Vega Marin",
                            Password = "41936"
                        });
                });

            modelBuilder.Entity("CreditFullSA.Models.Credito", b =>
                {
                    b.Property<int>("numeroSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("numeroSolicitud"));

                    b.Property<int>("cedula")
                        .HasColumnType("int");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("lineaCredito")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("montoInteres")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("montoSolicitar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("nombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("plazo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("numeroSolicitud");

                    b.ToTable("Creditos");
                });
#pragma warning restore 612, 618
        }
    }
}
